---
# auto-reboot linux 30 seconds after a kernel panic
- block:
    - name: set kernel.panic to 60
      sysctl:
        name: kernel.panic
        value: 60 # default 0

    - name: set kernel.panic_on_oops to 1
      sysctl:
        name: kernel.panic_on_oops
        value: 1 # default 0

- name: controls whether core dumps will append the pid to the core filename
  sysctl:
    name: kernel.core_uses_pid
    value: 1 # default 0

- name: allow for more pids
  sysctl:
    name: kernel.pid_max
    value: 4194304 # default 32768, 4194304 is max on x64 system

- name: controls the maximum size of a message, in bytes
  sysctl:
    name: kernel.msgmnb
    value: 65536 # default 16384

- name: controls the default maxmimum size of a mesage queue
  sysctl:
    name: kernel.msgmax
    value: 65536 # default 8192

# https://serverfault.com/questions/59824/shmmax-setting-in-sysctl-conf-not-taking-effect
# set maximum amount of memory allocated to shm to 256MB
# - block:
#     - name: set kernel.shmmax to 268435456
#       sysctl:
#         name: kernel.shmmax
#         value: 268435456 # default 33554432

#     - name: set kernel.shmall to 268435456
#       sysctl:
#         name: kernel.shmall
#         value: 268435456 # default 2097152
