---
- name: configure max open files
  sysctl:
    name: fs.file-max
    value: 65535

# do less swapping
- block:
    - name: set vm.swappiness to 1
      sysctl:
        name: vm.swappiness
        value: 1 # default 60

    - name: set vm.dirty_ratio to 80
      sysctl:
        name: vm.dirty_ratio
        value: 80 # default 20

    - name: set vm.dirty_background_ratio to 5
      sysctl:
        name: vm.dirty_background_ratio
        value: 5 # default 10

- name: specifies the minimum virtual address that a process is allowed to mmap
  sysctl:
    name: vm.mmap_min_addr
    value: 65535 # default 65535
