---
- name: prevent syn attack, enable syncookies (they will kick-in when the max_syn_backlog reached)
  block:
    - name: enable syn cookies
      sysctl:
        name: net.ipv4.tcp_syncookies
        value: 1

    - name: only retry creating tcp connections twice
      sysctl:
        name: net.ipv4.tcp_syn_retries
        value: 2

    - name: only retry creating TCP connections twice
      sysctl:
        name: net.ipv4.tcp_synack_retries
        value: 2

    - name: increase max half-open connections
      sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 8192

- name: disables packet forwarding
  block:
    - sysctl:
        name: net.ipv4.ip_forward
        value: 0

    - sysctl:
        name: net.ipv4.conf.all.forwarding
        value: 0

    - sysctl:
        name: net.ipv4.conf.default.forwarding
        value: 0

    - sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 0

    - sysctl:
        name: net.ipv6.conf.default.forwarding
        value: 0

- name: disables ip source routing
  block:
    - sysctl:
        name: net.ipv4.conf.all.send_redirects
        value: 0

    - sysctl:
        name: net.ipv4.conf.default.send_redirects
        value: 0

    - sysctl:
        name: net.ipv4.conf.all.accept_source_route
        value: 0

    - sysctl:
        name: net.ipv4.conf.default.accept_source_route
        value: 0

    - sysctl:
        name: net.ipv6.conf.all.accept_source_route
        value: 0

    - sysctl:
        name: net.ipv6.conf.default.accept_source_route
        value: 0

- name: allow reusing sockets in TIME_WAIT state for new connections
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1

- name: max rx/tx buffer size (16M)
  sysctl:
    name: "{{ item }}"
    value: 16777216
  with_items:
    - net.core.rmem_max
    - net.core.wmem_max
    - net.core.rmem_default
    - net.core.wmem_default

- name: max rx/tx buffer size for ipv4 (16M)
  sysctl:
    name: "{{ item }}"
    value: "4096 87380 16777216"
  with_items:
    - net.ipv4.tcp_rmem
    - net.ipv4.tcp_wmem

- name: specify the maximum buffer size allowed per socket
  sysctl:
    name: net.core.optmem_max
    value: 40960

- name: increase max number of sockets allowed in TIME_WAIT
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 2000000

- name: increase max half-open connections
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 30000

- name: increase max TCP orphans
  sysctl:
    name: net.ipv4.tcp_max_orphans
    value: 262144

- name: max listen queue backlog
  sysctl:
    name: net.core.somaxconn
    value: 262144

- name: max number of packets that can be queued on interface input
  sysctl:
    name: net.core.netdev_max_backlog
    value: 65536

- name: timeout closing of TCP connections after 10 seconds
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 10

- name: avoid falling back to slow start after a connection goes idle
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0

- name: determines the number of probes before timing out
  sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: 5

- name: determines the wait time between isAlive interval probes
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: 3

- name: disable TCP timestamps - saves 12 bytes
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: 0

- name: selectively acknowledge each segment in a TCP window
  sysctl:
    name: net.ipv4.tcp_sack
    value: 1

- name: enabling tcp window scaling
  sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1

- name: causes the kernel to actively send RST packets when a service is overloaded
  sysctl:
    name: net.ipv4.tcp_abort_on_overflow
    value: 1

- name: turn on protection for bad icmp error messages
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1

- name: turn on syncookies for SYN flood attack protection
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
