---
- name: allow reusing sockets in TIME_WAIT state for new connections
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1

- name: max rx/tx buffer size (16M)
  sysctl:
    name: "{{ item }}"
    value: 16777216
  with_items:
    - net.core.rmem_max
    - net.core.wmem_max
    - net.core.rmem_default
    - net.core.wmem_default

- name: max rx/tx buffer size for ipv4 (16M)
  sysctl:
    name: "{{ item }}"
    value: "4096 87380 16777216"
  with_items:
    - net.ipv4.tcp_rmem
    - net.ipv4.tcp_wmem

- name: specify the maximum buffer size allowed per socket
  sysctl:
    name: net.core.optmem_max
    value: 65536

- name: increase max number of sockets allowed in TIME_WAIT
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 2097152

- name: increase max TCP orphans
  sysctl:
    name: net.ipv4.tcp_max_orphans
    value: 16384

- name: max listen queue backlog
  sysctl:
    name: net.core.somaxconn
    value: 65536

- name: max number of packets that can be queued on interface input
  sysctl:
    name: net.core.netdev_max_backlog
    value: 65536

- name: timeout closing of TCP connections after 10 seconds
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 10

- name: avoid falling back to slow start after a connection goes idle
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0

- name: determines the number of probes before timing out
  sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: 5

- name: determines the wait time between isAlive interval probes
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: 3

- name: disable TCP timestamps - saves 12 bytes
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: 0

- name: enabling tcp window scaling
  sysctl:
    name: net.ipv4.tcp_window_scaling
    value: 1

- name: causes the kernel to actively send RST packets when a service is overloaded
  sysctl:
    name: net.ipv4.tcp_abort_on_overflow
    value: 1

- name: don't cache ssthresh from previous connection
  block:
    - sysctl:
        name: net.ipv4.tcp_no_metrics_save
        value: 1
    - sysctl:
        name: net.ipv4.tcp_moderate_rcvbuf
        value: 1
